apiVersion: apps/v1
kind: Deployment
metadata:
  name: pfdemo-deployment
spec:
 replicas: 1
 selector:
   matchLabels:
     app: pfdemo-app
 template:
   metadata:
     labels:
       app: pfdemo-app
   spec:
     volumes:
      - name: pfdemo-pvc
        emptyDir: {}
     containers:
     - name: pfdemo-app
       image: docker.io/fogartyp/pfdemo:latest
       imagePullPolicy: Always
       ports:
       - containerPort: 80
      #  volumeMounts:
      #     - name: pfdemo-pvc
      #       mountPath: /db #/database.db
            # subPath: database.db
    #  initContainers:
    #   - command:
    #       - /bin/sh
    #       - '-c'
    #       - '[[ -e "database.db" ]] && echo "database.db already exists." || (echo "Creating database.db..."; touch "database.db"; echo "database.db created.")'
    #     image: centos
    #     imagePullPolicy: Always
    #     name: init-container
    #     resources: {}
    #     terminationMessagePath: /dev/termination-log
    #     terminationMessagePolicy: File
    #     volumeMounts:
    #       - mountPath: /db
    #         name: pfdemo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: pfdemo-service
spec:
  type: LoadBalancer
  selector:
    app: pfdemo-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
