apiVersion: apps/v1
kind: Deployment
metadata:
  name: pfdemo-deployment
spec:
 replicas: 1
 selector:
   matchLabels:
     app: pfdemo-app
 template:
   metadata:
     labels:
       app: pfdemo-app
   spec:
     volumes:
      - name: pfdemo-pvc
        emptyDir: {}
     containers:
     - name: pfdemo-app
       image: docker.io/fogartyp/pfdemo:latest
       ports:
       - containerPort: 8080
       volumeMounts:
          - name: pfdemo-pvc
            mountPath: /database.db
     initContainers:
      - command:
          - /bin/sh
          - '-c'
          - 'echo "Hello World"'
        image: centos
        imagePullPolicy: Always
        name: init-container
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
          - mountPath: /
            name: pfdemo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: pfdemo-service
spec:
  type: LoadBalancer
  selector:
    app: pfdemo-app
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30001
